project:
  type: website

website:
  title: "INICIATIVA CIENCIA DE DATOS" 
  # Add site-url (without trailing / at the end)
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/Data-Science-Project-R-Python
        
format:
  html:
    theme: default

editor: source
