{
  "hash": "947aecf5a46b032c45aac61f06544f60",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: 'Student Performance (Multiple Linear Regression)'\nauthor: \"Jackeline García\"\ndate: '2023-08-09'\ncategories: ['Multiple linear regression']\nimage: \"image/image_jackeline.jpg\"\ndescription: 'Search the determinants of student perform using multiple regression analysis'\n---\n\n## Dataset information\n\n*Description:*\n\nThis research was from the Kaggle. The Student Performance Dataset is a dataset designed to examine the factors influencing academic student performance. The dataset consists of 10,000 student records, with each record containing information about various predictors and a performance index.\n\n*Variables:*\n\n-   Hours Studied: The total number of hours spent studying by each student.\n-   Previous Scores: The scores obtained by students in previous tests.\n-   Extracurricular Activities: Whether the student participates in extracurricular activities (Yes or No).\n-   Sleep Hours: The average number of hours of sleep the student had per day.\n-   Sample Question Papers Practiced: The number of sample question papers the student practiced.\n-   Performance Index: It represents the student's academic performance and has been rounded to the nearest whole number. The index ranges from 10 to 100, where higher values indicate better performance.\n\n## Multiple Regression Analysis: Step by step\n\n*Objective:* To identify the determinants of Student Performance.\n\n*Hypothesis:*\n\n-   H1: **Hours Studied** have a direct impact on **Performance Index**\n-   H2: **Previous Scores** have a direct impact on **Performance Index**\n-   H3: **Sample Question Papers Practiced** have a direct impact on **Performance Index**\n-   H4: **Sleep Hours** have a direct impact on **Performance Index**\n\n*Steps to prove the hypothesis*\n\nA. Model Evaluation\n\n1.  Regression coeficients and r-square\n2.  Interpretation\n\nB. Regression Model Assumtions\n\n1.  Lineality between dependent variables and independent variables.\n2.  Independence of observations: The observation from our model are independent.\n3.  Homoscedasticity: The errors from our model have equal variance.\n4.  Normality of Errors: The errors from our model are normally distributed.\n5.  Multicollinality: evaluate if the IVs are redundant.\n\n### Load the packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"foreign\")\nlibrary(ggplot2)\nlibrary(ggpubr)\nlibrary(dplyr)\nlibrary(broom)\nlibrary(ggpubr)\nlibrary(tidyverse)\nlibrary(readr)\nlibrary(car)\n```\n:::\n\n\n## A. Model Evaluation\n\n### A1. Regression coeficients and r-square\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMydata <- read_csv(\"data/Student_Performance.csv\")\nsummary(Mydata$Performance_Index)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  10.00   40.00   55.00   55.22   71.00  100.00 \n```\n\n\n:::\n:::\n\n\n### **Hours Studied ~ Performance_Index**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHoursStudied_lm <- lm(Performance_Index ~ Hours_Studied, data = Mydata) \nsummary(HoursStudied_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Performance_Index ~ Hours_Studied, data = Mydata)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-37.564 -15.244  -0.152  15.529  35.756 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   41.37917    0.38712  106.89   <2e-16 ***\nHours_Studied  2.77306    0.06883   40.29   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 17.82 on 9998 degrees of freedom\nMultiple R-squared:  0.1397,\tAdjusted R-squared:  0.1396 \nF-statistic:  1623 on 1 and 9998 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n###### Estimates:\n\nFor each additional hour of study, the student's performance index increased by **2.77** on average. This result was statistically significant.\n\n###### Coefficient of determination:\n\nThe model explains approximately 13.97% of the variability in the Performance_Index based on the hours of study.\n\n### **Previous Score ~ Performance_Index**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPreviousScore_lm <- lm(Performance_Index ~ Previous_Scores, data = Mydata) \nsummary(PreviousScore_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Performance_Index ~ Previous_Scores, data = Mydata)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-17.7729  -6.5239  -0.0082   6.3689  19.4346 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     -15.181799   0.319605   -47.5   <2e-16 ***\nPrevious_Scores   1.013837   0.004465   227.1   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.744 on 9998 degrees of freedom\nMultiple R-squared:  0.8376,\tAdjusted R-squared:  0.8376 \nF-statistic: 5.156e+04 on 1 and 9998 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n###### Estimates:\n\nFor each additional point earned on past exams, the student's performance index increased by **one point** on average. This result was statistically significant.\n\n###### Coefficient of determination:\n\nThe model explains approximately 83.76% of the variability in the Performance_Index from the previous score.\n\n### **Sample Question Papers Practiced ~ Performance_Index**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSample_Question_Papers_lm <- lm(Performance_Index ~ Sample_Question_Papers_Practiced, data = Mydata) \nsummary(Sample_Question_Papers_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Performance_Index ~ Sample_Question_Papers_Practiced, \n    data = Mydata)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-46.505 -15.056  -0.056  15.234  44.814 \n\nCoefficients:\n                                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                      53.89602    0.36194  148.91  < 2e-16 ***\nSample_Question_Papers_Practiced  0.28992    0.06695    4.33  1.5e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 19.2 on 9998 degrees of freedom\nMultiple R-squared:  0.001872,\tAdjusted R-squared:  0.001772 \nF-statistic: 18.75 on 1 and 9998 DF,  p-value: 1.503e-05\n```\n\n\n:::\n:::\n\n\n###### Estimates:\n\nFor each additional sample exam taken, the student's performance index increased by **0.28** on average. This result was statistically significant.\n\n###### Coefficient of determination:\n\nThe model explains only 0.18% of the variability in the Performance_Index based on the number of practice exams taken.\n\n### **Sleep Hours ~ Performance_Index**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSleepHours_lm <- lm(Performance_Index ~ Sleep_Hours, data = Mydata) \nsummary(SleepHours_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Performance_Index ~ Sleep_Hours, data = Mydata)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-45.571 -15.026  -0.026  15.429  46.154 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  51.6657     0.7636  67.662  < 2e-16 ***\nSleep_Hours   0.5450     0.1132   4.816 1.49e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 19.19 on 9998 degrees of freedom\nMultiple R-squared:  0.002314,\tAdjusted R-squared:  0.002214 \nF-statistic: 23.19 on 1 and 9998 DF,  p-value: 1.489e-06\n```\n\n\n:::\n:::\n\n\n###### Estimates:\n\nFor each additional hour of sleep, the student's performance index increased by **0.54** on average. This result was statistically significant.\n\n###### Coefficient of determination:\n\nThe model explains only 0.23% of the variability in the Performance_Index from the hours of sleep.\n\n## B. Multiple regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPerformance_lm <- lm(Performance_Index ~ Hours_Studied + Previous_Scores + Sample_Question_Papers_Practiced + Sleep_Hours, data = Mydata) \nsummary(Performance_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Performance_Index ~ Hours_Studied + Previous_Scores + \n    Sample_Question_Papers_Practiced + Sleep_Hours, data = Mydata)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8.3299 -1.3831 -0.0062  1.3701  8.4864 \n\nCoefficients:\n                                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                      -33.763726   0.126841 -266.19   <2e-16 ***\nHours_Studied                      2.853429   0.007962  358.40   <2e-16 ***\nPrevious_Scores                    1.018584   0.001189  857.02   <2e-16 ***\nSample_Question_Papers_Practiced   0.195198   0.007189   27.15   <2e-16 ***\nSleep_Hours                        0.476333   0.012153   39.19   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.061 on 9995 degrees of freedom\nMultiple R-squared:  0.9885,\tAdjusted R-squared:  0.9885 \nF-statistic: 2.147e+05 on 4 and 9995 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n### B1. Interpretation\n\n###### Estimates:\n\nFor each additional hour of study, the student's performance index increased by 2.85 on average. This result was statistically significant.\n\nFor each additional point earned on past exams, the student's performance index increased by one point on average. This result was statistically significant.\n\nFor each additional sample exam taken, the student's performance index increased by 0.19 on average. This result was statistically significant.\n\nFor each additional hour of sleep, the student's performance index increased by 0.47 on average. This result was statistically significant.\n\n###### Coefficient of determination:\n\nThe model explains approximately 98.85% of the variability in the Performance_Index using the variables hours studied, previous scores, sample question papers practiced, and sleep hours. This means that, together, these four variables offer an extremely accurate prediction of academic performance, much stronger than when analyzed separately.\n\n## c. Regression Model Assumtions\n\n### c1. Lineality between dependent variables and independent variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggscatter(x=\"Hours_Studied\", y=\"Performance_Index\", data = Mydata, add=\"reg.line\", add.params = list(color=\"red\", fill=\"gray70\"))\n```\n\n::: {.cell-output-display}\n![](jackeline_regression_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggscatter(x=\"Previous_Scores\", y=\"Performance_Index\", data = Mydata, add=\"reg.line\", add.params = list(color=\"red\", fill=\"gray70\"))\n```\n\n::: {.cell-output-display}\n![](jackeline_regression_files/figure-html/unnamed-chunk-8-2.png){width=672}\n:::\n\n```{.r .cell-code}\nggscatter(x=\"Sample_Question_Papers_Practiced\", y=\"Performance_Index\", data = Mydata, add=\"reg.line\", add.params = list(color=\"red\", fill=\"gray70\"))\n```\n\n::: {.cell-output-display}\n![](jackeline_regression_files/figure-html/unnamed-chunk-8-3.png){width=672}\n:::\n\n```{.r .cell-code}\nggscatter(x=\"Sleep_Hours\", y=\"Performance_Index\", data = Mydata, add=\"reg.line\", add.params = list(color=\"red\", fill=\"gray70\"))\n```\n\n::: {.cell-output-display}\n![](jackeline_regression_files/figure-html/unnamed-chunk-8-4.png){width=672}\n:::\n:::\n\n\n### c2. Independence of observations\n\nThe observation from our model are independent.\n\nThis was fulfilled when each observation was made by one participant.\n\n### B3. Homocedasticity\n\nThe errors from our model have equal variance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,2))\nplot(Performance_lm)\n```\n\n::: {.cell-output-display}\n![](jackeline_regression_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n### c4. Normality of Errors\n\nThe errors from our model are normally distributed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,2))\nplot(Performance_lm)\n```\n\n::: {.cell-output-display}\n![](jackeline_regression_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n### c5. Multicollinality: evaluate if the IVs are redundant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif(Performance_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   Hours_Studied                  Previous_Scores \n                        1.000464                         1.000254 \nSample_Question_Papers_Practiced                      Sleep_Hours \n                        1.000386                         1.000052 \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "jackeline_regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}